-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 16:24:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema competitions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema competitions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `competitions` DEFAULT CHARACTER SET utf8 ;
USE `competitions` ;

-- -----------------------------------------------------
-- Table `competitions`.`ATHLETE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`ATHLETE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `dateOfBirth` DATE,
  `value` BIGINT,
  `valueCurrency` VARCHAR(20),
  `position` VARCHAR(250),
  `nationality` VARCHAR(250),
  PRIMARY KEY (`id`))
ENGINE = InnoDB AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `competitions`.`TEAM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`TEAM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(250) NOT NULL,
  `shortName` VARCHAR(5) NOT NULL,
  `foundingDate` DATE,
  `teamValue` BIGINT,
  `valueCurrency` VARCHAR(20),
  `imageLink` VARCHAR(250),
  `homePlace` VARCHAR(250),
  PRIMARY KEY (`id`))
ENGINE = InnoDB AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `competitions`.`PLAYS_IN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`PLAYS_IN` (
  `athlete_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `jersey_number` INT,
  `start_of_contract` DATE NOT NULL,
  `end_of_contract` DATE,
  PRIMARY KEY (`athlete_id`, `team_id`, `start_of_contract`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `pi_athlete_id`
    FOREIGN KEY (`athlete_id`)
    REFERENCES `competitions`.`ATHLETE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pi_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`STAFF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`STAFF` (
  `id` VARCHAR(6) NOT NULL,
  `name` VARCHAR(250),
  `work` VARCHAR(250),
  `date_of_birth` DATE,
  `nationalitiy` VARCHAR(250),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`WORKS_IN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`WORKS_IN` (
  `staff_id` VARCHAR(6) NOT NULL,
  `team_id` INT NOT NULL,
  `start_of_contract` DATE NOT NULL,
  `end_of_contract` DATE,
  PRIMARY KEY (`staff_id`, `team_id`, `start_of_contract`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `wi_staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `competitions`.`STAFF` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wi_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`COMPETITION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`COMPETITION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(250),
  `sportType` VARCHAR(250),
  `name` VARCHAR(250),
  `logoLink` VARCHAR(250),
  PRIMARY KEY (`id`))
ENGINE = InnoDB AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `competitions`.`SEASON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`SEASON` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `competitionId` INT NOT NULL,
  `started` DATE,
  `finished` DATE,
  PRIMARY KEY (`id`),
  INDEX `competitionIdIdx` (`competitionId` ASC) VISIBLE,
  CONSTRAINT `seCompetitionId`
    FOREIGN KEY (`competitionId`)
    REFERENCES `competitions`.`COMPETITION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------
-- Table `competitions`.`IN_SEASON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`IN_SEASON` (
  `seasonId` INT NOT NULL,
  `teamId` INT NOT NULL,
  PRIMARY KEY (`seasonId`, `teamId`),
  INDEX `seasonIdIdx` (`seasonId` ASC) VISIBLE,
  INDEX `teamIdIdx` (`teamId` ASC) VISIBLE,
  CONSTRAINT `inseSeasonId`
    FOREIGN KEY (`seasonId`)
    REFERENCES `competitions`.`SEASON` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inseTeamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------
-- Table `competitions`.`MATCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`MATCH` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seasonId` INT,
  `homeTeam` INT NOT NULL,
  `awayTeam` INT NOT NULL,
  `homeScore` INT,
  `awayScore` INT,
  `place` VARCHAR(250),
  `date` DATE,
  PRIMARY KEY (`id`),
  INDEX `seasonIdIdx` (`seasonId` ASC) VISIBLE,
  INDEX `homeTeamIdx` (`homeTeam` ASC) VISIBLE,
  INDEX `awayTeamIdx` (`awayTeam` ASC) VISIBLE,
  CONSTRAINT `maSeasonId`
    FOREIGN KEY (`seasonId`)
    REFERENCES `competitions`.`SEASON` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `maHomeTeam`
    FOREIGN KEY (`homeTeam`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `maAwayTeam`
    FOREIGN KEY (`awayTeam`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `competitions`.`PLAYED_MATCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`PLAYED_MATCH` (
  `athleteId` INT NOT NULL,
  `matchId` INT NOT NULL,
  `timePlayed` DATETIME,
  `playingStarted` DATETIME,
  PRIMARY KEY (`athleteId`, `matchId`),
  INDEX `matchIdIdx` (`matchId` ASC) VISIBLE,
  CONSTRAINT `pmAthleteId`
    FOREIGN KEY (`athleteId`)
    REFERENCES `competitions`.`ATHLETE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pmMatchId`
    FOREIGN KEY (`matchId`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`EVENT_TYPES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`EVENT_TYPES` (
  `id` INT NOT NULL,
  `type` VARCHAR(250),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`EVENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`EVENT` (
  `athleteId` INT NOT NULL,
  `teamId` INT NOT NULL,
  `matchId` INT NOT NULL,
  `eventType` INT NOT NULL,
  `time` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`athleteId`, `teamId`, `matchId`, `time`),
  INDEX `teamIdIdx` (`teamId` ASC) VISIBLE,
  INDEX `matchIdIdx` (`matchId` ASC) VISIBLE,
  INDEX `eventTypeIdx` (`eventType` ASC) VISIBLE,
  CONSTRAINT `evAthleteId`
    FOREIGN KEY (`athleteId`)
    REFERENCES `competitions`.`ATHLETE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evTeamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evMatchId`
    FOREIGN KEY (`matchId`)
    REFERENCES `competitions`.`MATCH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evEventType`
    FOREIGN KEY (`eventType`)
    REFERENCES `competitions`.`EVENT_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`AM_FOOTBALL_MATCHSTATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`AM_FOOTBALL_MATCHSTATS` (
  `id` INT NOT NULL,
  `hTouchdowns` INT,
  `aTouchdowns` INT,
  `hFieldGoals` INT,
  `aFieldGoals` INT,
  `hExtraPoint` INT,
  `aExtraPoint` INT,
  `hTwoPoint` INT,
  `aTwoPoint` INT,
  `hTotalYards` INT,
  `aTotalYards` INT,
  `hPassingYards` INT,
  `aPassingYards` INT,
  `hRushingYards` INT,
  `aRushingYards` INT,
  `hAvgYrdsPerPlay` DECIMAL,
  `aAvgYrdsPerPlay` DECIMAL,
  `hFumbles` INT,
  `aFumbles` INT,
  `hInterceptions` INT,
  `aInterceptions` INT,
  `hPunts` INT,
  `aPunts` INT,
  `hTimeOfPossession` VARCHAR(6),
  `aTimeOfPossession` VARCHAR(6),
  `hPenalties` INT,
  `aPenalties` INT,
  `hYardsPenalized` INT,
  `aYardsPenalized` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `afstatMatchId`
    FOREIGN KEY (`id`)
    REFERENCES `competitions`.`MATCH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`HANDBALL_MATCHSTATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`HANDBALL_MATCHSTATS` (
  `id` INT NOT NULL,
  `hShootingEfficiency` DECIMAL,
  `aShootingEfficiency` DECIMAL,
  `hWingGoals` INT,
  `aWingGoals` INT,
  `hFastbreakGoals` INT,
  `aFastbreakGoals` INT,
  `hSevenMeters` INT,
  `aSevenMeters` INT,
  `hSaves` INT,
  `aSaves` INT,
  `hTwoMinPenalty` INT,
  `aTwoMinPenalty` INT,
  `hYellowCards` INT,
  `aYellowCards` INT,
  `hGoalStreak` INT,
  `aGoalStreak` INT,
  `hGoalsInPowerplay` INT,
  `aGoalsInPowerplay` INT,
  `hShorthandedGoals` INT,
  `aShorthandedGoals` INT,
  `hSteals` INT,
  `aSteals` INT,
  `hTechnicalFaults` INT,
  `aTechnicalFaults` INT,
  `hTimeouts` INT,
  `aTimeouts` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `hastatMatchId`
    FOREIGN KEY (`id`)
    REFERENCES `competitions`.`MATCH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`FOOTBALL_MATCHSTATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`FOOTBALL_MATCHSTATS` (
  `id` INT NOT NULL,
  `hAttempts` INT,
  `aAttempts` INT,
  `hOnTarget` INT,
  `aOnTarget` INT,
  `hCorners` INT,
  `aCorners` INT,
  `hOffsides` INT,
  `aOffsides` INT,
  `hPossession` DECIMAL,
  `aPossession` DECIMAL,
  `hPassingAccuracy` DECIMAL,
  `aPassingAccuracy` DECIMAL,
  `hPasses` INT,
  `aPasses` INT,
  `hPassesCompleted` INT,
  `aPassesCompleted` INT,
  `hYellow` INT,
  `aYellow` INT,
  `hRed` INT,
  `aRed` INT,
  `hFouls` INT,
  `aFouls` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fstatMatchId`
    FOREIGN KEY (`id`)
    REFERENCES `competitions`.`MATCH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`BASKETBALL_MATCHSTATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`BASKETBALL_MATCHSTATS` (
  `id` INT NOT NULL,
  `hFreeThrows` INT,
  `aFreeThrows` INT,
  `hTwoPointers` INT,
  `aTwoPointers` INT,
  `hThreePointers` INT,
  `aThreePointers` INT,
  `hFieldGoals` INT,
  `aFieldGoals` INT,
  `hRebounds` INT,
  `aRebounds` INT,
  `hTurnovers` INT,
  `aTurnovers` INT,
  `hSteals` INT,
  `aSteals` INT,
  `hBlocks` INT,
  `aBlocks` INT,
  `hFouls` INT,
  `aFouls` INT,
  `hTimeouts` INT,
  `aTimeouts` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `bstatMatchId`
    FOREIGN KEY (`id`)
    REFERENCES `competitions`.`MATCH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`HOCKEY_MATCHSTATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`HOCKEY_MATCHSTATS` (
  `id` INT NOT NULL,
  `hShots` INT,
  `aShots` INT,
  `hGoalsInPowerplay` INT,
  `aGoalsInPowerplay` INT,
  `hShorthandedGoals` INT,
  `aShorthandedGoals` INT,
  `hFaceoffsWon` INT,
  `aFaceoffsWon` INT,
  `hBlocked` INT,
  `aBlocked` INT,
  `hTakeaways` INT,
  `aTakeaways` INT,
  `hGiveaways` INT,
  `aGiveaways` INT,
  `hPenaltyMinutes` INT,
  `aPenaltyMinutes` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `hostatMatchId`
    FOREIGN KEY (`id`)
    REFERENCES `competitions`.`MATCH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`AM_FOOTBALL_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`AM_FOOTBALL_TABLE` (
  `season_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `position` INT,
  `wins` INT,
  `loses` INT,
  `pct` DECIMAL,
  PRIMARY KEY (`season_id`, `team_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `aftable_season_id`
    FOREIGN KEY (`season_id`)
    REFERENCES `competitions`.`SEASON` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aftable_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`BASKETBALL_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`BASKETBALL_TABLE` (
  `season_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `position` INT,
  `played` INT,
  `wins` INT,
  `loses` INT,
  `pct` INT,
  `str` DECIMAL,
  PRIMARY KEY (`season_id`, `team_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `btable_season_id`
    FOREIGN KEY (`season_id`)
    REFERENCES `competitions`.`SEASON` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `btable_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`HANDBALL_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`HANDBALL_TABLE` (
  `season_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `position` INT,
  `played` INT,
  `wins` INT,
  `draws` INT,
  `loses` INT,
  `diff` INT,
  `points` INT,
  PRIMARY KEY (`season_id`, `team_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `hatable_season_id`
    FOREIGN KEY (`season_id`)
    REFERENCES `competitions`.`SEASON` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hatable_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`FOOTBALL_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`FOOTBALL_TABLE` (
  `season_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `position` INT,
  `played` INT,
  `wins` INT,
  `draws` INT,
  `loses` INT,
  `for` INT,
  `against` INT,
  `goal_diff` INT,
  `points` INT,
  PRIMARY KEY (`season_id`, `team_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `ftable_season_id`
    FOREIGN KEY (`season_id`)
    REFERENCES `competitions`.`SEASON` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ftable_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitions`.`HOCKEY_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competitions`.`HOCKEY_TABLE` (
  `season_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `position` INT,
  `played` INT,
  `wins` INT,
  `loses` INT,
  `points` INT,
  `wp` INT,
  `lp` INT,
  `str` INT,
  PRIMARY KEY (`season_id`, `team_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `hotable_season_id`
    FOREIGN KEY (`season_id`)
    REFERENCES `competitions`.`SEASON` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hotable_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `competitions`.`TEAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;